### ISSUE TITLE
[Release]: v 0.6.0 & 0.6.0-arduino

### ISSUE THREAD

**Issue by sleepdefic1t** [ArkEcosystem/cpp-crypto#110]
After merging of #107, #108, & #109, 
both--the develop and arduino--branches will be ready to be tagged and released.

Please and thank you, @faustbrian

**Comment by sleepdefic1t** [comment]
@faustbrian 
Anything else needed before we tag and release v.0.6.0?

**Comment by faustbrian** [comment]
@sleepdefic1t if you update the changelogs with all changes since the last release I can tag the 0.6.0 releases.

**Comment by sleepdefic1t** [comment]
Released 2019-07-16
