### ISSUE TITLE
Setup Windows for GitHub Actions

### ISSUE THREAD

**Issue by faustbrian** [ArkEcosystem/cpp-crypto#144]
https://github.com/ArkEcosystem/cpp-crypto/commit/b05116d6ab4ffe50cad53a49ca33e95ec505064f moved everything CI related to GitHub Actions. Missing is windows to ditch appveyor which is a bit unreliable.

**Comment by faustbrian** [comment]
@ciband @sleepdefic1t could you look into what configurations you need to get the tests and build working on GitHub Actions with windows? Should be fairly simple like the rest of the workflows.

**Comment by faustbrian** [comment]
I pushed some basic config here https://github.com/ArkEcosystem/cpp-crypto/commit/92a08b1d86ce7c87e4906c3d9c762d9702dcca75. It seems to replicate what Appveyor does based on their logs but the `test/Debug` folder doesn't seem to ever exist after building but never been a Windows user so don't really know anything about that OS.

**Comment by ciband** [comment]
Looking at this now
