### ISSUE TITLE
CircleCI MacOS builds Inop

### ISSUE THREAD

**Issue by ciband** [ArkEcosystem/cpp-crypto#27]
**Describe the bug**
When CircleCI builds are triggered by PRs, the MacOS builds are not firing.

**To Reproduce**
1. Submit any PR to the repo
2. Observe that the macOS builds do not work and prompt to choose a macOS plan (paid plan)

**Expected behavior**
I would expect the macOS builds to work like they did in TravisCI.

**Screenshots**
N/A

**Server (please complete the following information):**
N/A

**Additional context**
cpp-client does not seem to have this issue.  I assume it is something administrative.

**Comment by sleepdefic1t** [comment]
Related Issue also discussed in https://github.com/ArkEcosystem/cpp-client/issues/55

**Comment by sleepdefic1t** [comment]
#46, and #47  (submitted myself) builds and passes all tests including macOS.


The following three PR's (also submitted by me) in Cpp-Client trigger macOS builds which pass all tests including macOS:
- https://github.com/ArkEcosystem/cpp-client/pull/57
- https://github.com/ArkEcosystem/cpp-client/pull/58
- https://github.com/ArkEcosystem/cpp-client/pull/59

The following PR from @ciband did not trigger macOS builds:
- https://github.com/ArkEcosystem/cpp-client/pull/56

Overall, macOS builds seem to fail sporadically.
That could just be something funky on CircleCI's end.

PR's from other users continue to not trigger macOS builds.
PR's from myself continue to trigger macOS builds.

**Comment by faustbrian** [comment]
The issue is simply that @ciband is not on a paid plain on CircleCI and because he works on a fork the tests won't run for macOS.

I've added him as a contributor 1-2 weeks ago so he could work in branches so the macOS tests would work.

**Comment by ciband** [comment]
@faustbrian 

I would think that circleci should run all PRs against the ArkEcosystem repo with the ArkEcosystem account, not the Github user who may or may not have a circleci account.  This is how TravisCI worked (I believe).

Are we sure there isn't some circleci config that we might be missing?

As far as working directly in ArkEcosystem branches, I don't like that idea.  The beauty of the GitHub workflow is the PR system from forks.  We do a similar work flow in my day job with Gerrit.

Obviously, I can work in the Ark repo and still do PRs, but we shouldn't have/need to.

Ideal state should be full PR checks to run for any PR for anyone who wants to contribute.

Not trying stir anything up, but that is my 2 sats.  If I had the rights, I would attempt to investigate.

**Comment by faustbrian** [comment]
Once you fork the repository you get your own CircleCI repository for which you have no paid macOS plan which results in those tests not running/failing.

We use CircleCI instead of TravisCI because we had tons of timeout issues, even on the paid plan, and the performance of TravisCI is a joke compared to CircleCI which in a lot of repositories results in saving several minutes of runtime.

**Comment by sleepdefic1t** [comment]
@faustbrian I don't have a paid plan and am able to trigger macOS builds though.
I also do not have write access to manually rerun workflows 🤷‍♂️ 

Am I added anywhere in CI that allows this?
Or are there organizational settings that permit accounts with the `@ark.io` domain to trigger macOS?

**Comment by faustbrian** [comment]
Probably because you are a member of the ArkEcosystem organisation. You can go to any of cibands failed test macOS runs and it will have a big, fat yellow banner that says `Sorry! Your build didn't run because it looks like you haven't selected a macOS plan yet. If you have any questions, please feel free to contact us in support.`.
