### ISSUE TITLE
Prep for Arduino IDE Release of Cpp-Crypto

### ISSUE THREAD

**Issue by sleepdefic1t** [ArkEcosystem/cpp-crypto#65]
For Cpp-Crypto to be released in the Arduino IDE, the following must be done:
1) Create "arduino" branch.
2) Merge `https://github.com/sleepdefic1t/cpp-crypto/tree/arduino` to the "arduino" branch.
3) Tag/Release `0.3.0-arduino` targeting the "arduino" branch (**\*first**).
4) Tag/Release `0.3.0` targeting Master (**\*second**).

@faustbrian @kristjank @supaiku0 
At this time, I need an "arduino" branch.
After my PR is merged to the "arduino" branch, we can proceed with release/tagging.

**Comment by faustbrian** [comment]
https://github.com/ArkEcosystem/cpp-crypto/tree/arduino

Let me know when you made the changes needed so I tag the arduino release.

**Comment by sleepdefic1t** [comment]
@faustbrian #67

**Comment by faustbrian** [comment]
https://github.com/ArkEcosystem/cpp-crypto/releases/tag/0.3.0-arduino
