### ISSUE TITLE
PlatformIO builds fail with bip39 package on ESP8266.

### ISSUE THREAD

**Issue by sleepdefic1t** [ArkEcosystem/cpp-crypto#81]
**Describe the bug**

Builds fail with [bip39](https://github.com/ciband/bip39) package on ESP8266, most recent at:  #80 

A PR has been sitting at packages main repo as a potential fix: https://github.com/ciband/bip39/pull/8

There is a standing issue with repeating words in mnemonic generation brought up in #72 

There are also imposed limitations on micro-architectural environments pertaining to library size due to its multi-language dictionary. 

BIP39 is a nice feature to have, but this current implementation is buggy and out of scope for ARK SDK standards ([ARK SDK Cryptography Guidelines](https://docs.ark.io/sdk/cryptography/guidelines.html)).

I propose the bip39 lib be removed from the C++ Crypto SDK at this time.

Once its issues are addressed, I would like to see this listed as a C++ Crypto compatible lib in any relevant docs or media as an option for users; just not included by default.

Leaving this up for a few days to gather feedback if anyone wishes to weigh in.

**Comment by ciband** [comment]
I agree with Simon. 

Life has hit me and have been busy. I do not foresee time to be able to look into the outstanding bug in BIP39. 

It makes sense to drop support.

**Comment by sleepdefic1t** [comment]
Thank you, and no worries @ciband 

BIP39 support will be dropped soon then along with the mnemonic class and tests.

It will constitute a major version bump, and will likely come this week.
After that, I'll close out this issue.

**Comment by sleepdefic1t** [comment]
Resolved in #86
