### ISSUE TITLE
feat: add support for 255 bytes vendorfield

### ISSUE THREAD

**Issue by ItsANameToo** [ArkEcosystem/cpp-crypto#82]
The codebase needs to be updated to allow for the new 255 byte vendorfield size. Changes will be needed here: https://github.com/ArkEcosystem/cpp-crypto/blob/master/src/transactions/transaction.cpp#L90 .

Changes include:
- allow 255 bytes as maximum
- pad up to 64 bytes if vendorfield < 64 bytes
- if vendorfield size is between 64 and 255 bytes, no need to pad

**Comment by sleepdefic1t** [comment]
Resolved in #84 

This issue can now be closed, @faustbrian
