### ISSUE TITLE
Travis build badge not fully working

### ISSUE THREAD

**Issue by ciband** [ArkEcosystem/cpp-crypto#9]
**Describe the bug**
When you click on the Travis-CI build badge, Travis-CI reports that the repository has not been setup and you cannot view the build history.  The repo might just need to be enabled in Travis by an admin.

**To Reproduce**
1. Click the Travis build badge in the readme.md
2. The link will open the Travis webpage.
3. Observe the error.

**Expected behavior**
I would expect the badge to reflect the status of the last build for the current branch and then link allow me to view the build history in Travis for that branch.

**Screenshots**
N/A

**Server (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by ciband** [comment]
If we are migrating to circle CI then this can be closed since I assume that effort will give the page a CircleCI build badge

**Comment by sleepdefic1t** [comment]
We can close this issue. Repo is currently being migrated to CircleCI.
