### ISSUE TITLE
Implement AIP11

### ISSUE THREAD

**Issue by faustbrian** [ArkEcosystem/cpp-crypto#90]
https://github.com/ArkEcosystem/AIPs/blob/master/AIPS/aip-11.md

See https://github.com/ArkEcosystem/core/tree/master/packages/crypto/src for reference once Core 2.6 is released.

**Comment by sleepdefic1t** [comment]
## Status update:

~95% done.
Mostly documentation and a few small changes left.

https://github.com/users/sleepdefic1t/projects/2

**Comment by sleepdefic1t** [comment]
#198 merged to develop.
